project:
  type: manuscript

manuscript:
  article: 0_main_file.qmd

format:
  html:
    comments:
      hypothesis: true
    number-sections: true
  docx: 
    number-sections: true
  pdf: 
    number-sections: true

execute:
  freeze: true



